### ISSUE TITLE
NetAdapter  WHLK Test [PM_WolMagicPacket]   BSOD

### ISSUE THREAD

**Issue by lvwh2003** [Microsoft/Network-Adapter-Class-Extension#18]
We Have A NetAdapterCx Client Driver that Can Wol On Magic Packet/Pattern packet. When Send A Magic Packet to NetAdapterCx Client,The Client Will Crashes on   Report the Wake Reason Packet .When I Debug With the  Network-Adapter-Class-Extension Code,I Don't Find The Crash Reason On Code Line "netcx\adapter\nxadapterapi.cpp @ 1620"。   
         Could You Give Me Some Suggests Or  Share Me The Code With The Question。

STACK_TEXT:  
fffffd80`665b1378 fffff803`4a9e63d0     : 00000000`0000019e 00000000`0000002f 00000000`00000000 00000000`00000000 : nt!KeBugCheckEx
fffffd80`665b1380 fffff803`4a9d501a     : ffffe300`00000065 fffff803`5ba56d10 00000000`00000000 00000000`00000000 : Wdf01000!FxVerifierDriverReportedBugcheck+0x38 [minkernel\wdf\framework\shared\object\fxverifierbugcheck.cpp @ 192] 
fffffd80`665b13c0 fffff803`5bb5fe5d     : 00000000`00000000 ffffd18d`841f4dd0 ffffd18d`859adde8 00000000`00000000 : Wdf01000!imp_WdfCxVerifierKeBugCheck+0x6a [minkernel\wdf\framework\shared\core\verifierapi.cpp @ 230] 
fffffd80`665b1410 fffff803`5bb502af     : ffffd18d`7f749090 ffffd18d`8342ef98 fffff803`4aa2d900 fffffd80`665b1930 : NetAdapterCx!Verifier_ReportViolation+0x95 [minio\netcx\adapter\verifier.cpp @ 114] 
fffffd80`665b1460 fffff803`5ba4ed03     : ffffd18d`80ff4c10 ffffd18d`859adde8 00000000`00000000 00000000`00000001 : NetAdapterCx!imp_NetAdapterReportWakeReasonPacket+0x9f [minio\netcx\adapter\nxadapterapi.cpp @ 1620] 
fffffd80`665b14a0 fffff803`5ba4e36d     : 00002e72`7b8f0d18 ffffd18d`8342ef98 00000000`00000008 00000000`00000065 : ytcx21x64!NetAdapterReportWakeReasonPacket+0x43 [C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\km\netcx\kmdf\adapter\2.3\netadapter.h @ 1603] 
fffffd80`665b14e0 fffff803`5ba4dc57     : ffffd18d`83424030 00000000`00000001 00000000`00000008 00000000`00000065 : ytcx21x64!FxAdapterWpiDetection+0x1dd [E:\work\fuxi\code\gerrit_fuxi\fuxi\windows\NetAdapaterCx\fuxi_power.c @ 169] 
fffffd80`665b1580 fffff803`5ba4d70c     : ffffd18d`83424030 00000000`00000001 00000000`00000008 00000000`00000065 : ytcx21x64!FxAdapterRaiseToD0+0xe7 [E:\work\fuxi\code\gerrit_fuxi\fuxi\windows\NetAdapaterCx\fuxi_power.c @ 265] 
fffffd80`665b15e0 fffff803`4aa0d3e2     : 00002e72`7d468328 00000000`00000004 00000000`0000000e 00000000`00000015 : ytcx21x64!EvtDeviceD0Entry+0x6c [E:\work\fuxi\code\gerrit_fuxi\fuxi\windows\NetAdapaterCx\fuxi_power.c @ 656] 
fffffd80`665b1650 fffff803`4a9b06a2     : ffffd18d`859adde8 ffffd18d`82b97cd0 fffff803`4aa2df60 00000000`00000300 : Wdf01000!FxPnpDeviceD0Entry::InvokeClient+0x22 [minkernel\wdf\framework\shared\irphandlers\pnp\pnpcallbacks.cpp @ 93] 
fffffd80`665b16b0 fffff803`4aa10a1d     : ffffd18d`859ad8b0 fffffd80`665b1820 fffff803`4aa2df60 fffffd80`665b1930 : Wdf01000!FxPrePostCallback::InvokeStateful+0x94 [minkernel\wdf\framework\shared\irphandlers\pnp\cxpnppowercallbacks.cpp @ 291] 
fffffd80`665b16f0 fffff803`4aa0f1bf     : ffffd18d`859ad800 fffffd80`665b1820 fffff803`4aa2d920 00000000`00000000 : Wdf01000!FxPkgPnp::PowerWaking+0x3d [minkernel\wdf\framework\shared\irphandlers\pnp\powerstatemachine.cpp @ 3549] 
fffffd80`665b1720 fffff803`4aa10197     : fffff803`48c665b0 fffff803`4aa21dc0 00000000`00000001 00000000`000003e0 : Wdf01000!FxPkgPnp::PowerEnterNewState+0x193 [minkernel\wdf\framework\shared\irphandlers\pnp\powerstatemachine.cpp @ 1699] 
fffffd80`665b1860 fffff803`4aa11172     : fffffd80`665b1930 00000000`00000000 ffffd18d`859adab8 00000000`00000000 : Wdf01000!FxPkgPnp::PowerProcessEventInner+0x177 [minkernel\wdf\framework\shared\irphandlers\pnp\powerstatemachine.cpp @ 1613] 
fffffd80`665b18e0 fffff803`4aa21ac0     : ffffd18d`859adab0 ffffd18d`859ada90 ffffd18d`84524180 ffffd18d`845241c6 : Wdf01000!FxPkgPnp::_PowerProcessEventInner+0x32 [minkernel\wdf\framework\shared\irphandlers\pnp\powerstatemachine.cpp @ 1447] 
fffffd80`665b1910 fffff803`4aa21dcc     : ffffd18d`847853a0 ffffd18d`825b7de0 ffffd18d`00000000 00000000`00000000 : Wdf01000!FxEventQueue::EventQueueWorker+0x74 [minkernel\wdf\framework\shared\irphandlers\pnp\eventqueue.cpp @ 277] 
fffffd80`665b1960 fffff803`48c666b0     : 00000000`7c89b560 ffffd18d`7c9d2c40 00000000`00000000 00000000`00000000 : Wdf01000!FxThreadedEventQueue::_WorkItemCallback+0xc [minkernel\wdf\framework\shared\irphandlers\pnp\eventqueue.cpp @ 437] 
fffffd80`665b1990 fffff803`48d526e5     : ffffd18d`7a2ccbb0 ffffd18d`84524040 fffffd80`665b1b00 ffffd18d`00000000 : nt!IopProcessWorkItem+0x100
fffffd80`665b1a00 fffff803`48d569f7     : ffffd18d`84524040 00000000`00000750 ffffd18d`84524040 fffff803`48d52590 : nt!ExpWorkerThread+0x155
fffffd80`665b1bf0 fffff803`48e33be4     : fffff803`44037180 ffffd18d`84524040 fffff803`48d569a0 00000000`00000246 : nt!PspSystemThreadStartup+0x57
fffffd80`665b1c40 00000000`00000000     : fffffd80`665b2000 fffffd80`665ac000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x34

**Comment by amrutha-chandramohan** [comment]
Verifier violations can be mapped to the failure reason based on the bugcheck parameter – the FailureCode enums are defined [here](https://github.com/microsoft/Network-Adapter-Class-Extension/blob/de9490339b44f888aa2b302dc971f76789876950/netcx/adapter/verifier.hpp#L76).

The code on Github is slightly out of sync from the latest insider builds as it’s from an official release so the line numbers mentioned will not match. The function here is NetAdapterReportWakeReasonPacket in  [nxadapterapi.cpp](https://github.com/microsoft/Network-Adapter-Class-Extension/blob/de9490339b44f888aa2b302dc971f76789876950/netcx/adapter/nxadapterapi.cpp#L1530).
```
_IRQL_requires_(PASSIVE_LEVEL)
void
NETEXPORT(NetAdapterReportWakeReasonPacket)(
    _In_ NET_DRIVER_GLOBALS * DriverGlobals,
    _In_ NETADAPTER Adapter,
    _In_ const NET_ADAPTER_WAKE_REASON_PACKET * Reason
    )
{
    auto const nxPrivateGlobals = GetPrivateGlobals(DriverGlobals);
    Verifier_VerifyPrivateGlobals(nxPrivateGlobals);
    Verifier_VerifyIrqlPassive(nxPrivateGlobals);

    auto nxAdapter = GetNxAdapterFromHandle(Adapter);
    nxAdapter->ReportWakeReasonPacket(Reason);
}
```
Based on the stack, the  bugcheck may be due to three reasons:
1.	The DriverGlobals  is invalid
2.	Current IRQL level is not Passive
3.	The wake reason was reported outside of the interval between [EvtDeviceWakeFrom[S0/Sx]Triggered](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfdevice/nc-wdfdevice-evt_wdf_device_wake_from_s0_triggered) and [EvtDeviceDisarmWakeFrom[S0/Sx]](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfdevice/nc-wdfdevice-evt_wdf_device_disarm_wake_from_s0). This verification occurs in the Verifier_VerifyNetPowerUpTransition function in [ReportWakeReasonPacket](https://github.com/microsoft/Network-Adapter-Class-Extension/blob/de9490339b44f888aa2b302dc971f76789876950/netcx/adapter/nxadapter.cpp#L4059C39-L4059C39).

I see the wake reason is being indicated in EvtDeviceD0Entry in the stack provided so the bugcheck is due to reason 3 above – the wake reason was indicated too soon.

**Comment by lvwh2003** [comment]
Thanks for your message@amrutha . I tried to move the indication  to other  functions. so far there has been no success in reporting the indication packet。
